services:
  app:
    build:
      context: .
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_BACKEND_URL=http://localhost:4000
        # Optional Features
        - VITE_GEMINI_API=${VITE_GEMINI_API}
        - VITE_FIREBASE_API=${VITE_FIREBASE_API:-}
        - VITE_FIREBASE_DOMAIN=${VITE_FIREBASE_DOMAIN:-}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID:-}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET:-}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID:-}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID:-}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID:-}
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_FRONTEND_URL=http://localhost:4000